### ISSUE TITLE
Guido is literally my name, and it's in here

### ISSUE THREAD

**Issue by GuidoBelluomo** [zacanger/profane-words#10]
Please, remove it

**Comment by johnnyxmas** [comment]
Many normal, unoffensive names and words have been made commonly profane. As an Italian American, I've had this one lobbed against me for decades with some real stank on it. It's unfortunate but true. I m at least pleased to hear you've never experienced this (or perhaps you thought people just knew your name?)

**Comment by GuidoBelluomo** [comment]
> 

Hi, my main issue is that some places seem to be implementing such lists even in their first name fields and similar data inputs. I literally cannot input my name without triggering filters.

**Comment by zautumnz** [comment]
Done
