### ISSUE TITLE
Menses, menstruate, menstruation are proper terms with no inherently profane connotations

### ISSUE THREAD

**Issue by johnnyxmas** [zacanger/profane-words#11]
Marking these appropriate terms as profane furthers a fear and subsequent disgust of the body's function. We should embrace their discussion and use. Yes, we should still mark phrases such as "raggin'" and "on the rag" are profane, but these terms here are the ones we WANT people to be able to use in discussion.

**Comment by zautumnz** [comment]
Thanks, you're right. Fixed.
