### ISSUE TITLE
List of violent words to filter?

### ISSUE THREAD

**Issue by RheingoldRiver** [zacanger/profane-words#12]
Hi,
For my discord bot we're making an April Fools Day feature where she spits out random words as a fake "chatGPT" "algorithm." For this use case, "inappropriate words" includes anything at all violent, so we need to filter out both profane words and also violent words. I've always used this filter for profane words, but I don't know of any filter for violent words.' Do you know of one? For example, I'd want words like "gun" and "knife" removed.

Thanks!

**Comment by zautumnz** [comment]
Hey River, I don't know of one offhand. A quick search on GitHub returned [this repo](https://github.com/Uncharacteristically/blockbadwords/tree/main/explicit-words-lists), but `violent.txt` list there is definitely lacking. Looks like maybe there's a need for someone to come up with a comprehensive list!

**Comment by RheingoldRiver** [comment]
Thanks for the reply! I'll use that one as a start for now, and see what happens during testing, probably I'll add some words to it as well and open a PR to improve it. We were also thinking of seeing if we can find some library that affects the temperature of the words that we select, so maybe we can skew that way as well.
