### ISSUE TITLE
False positive suggestions

### ISSUE THREAD

**Issue by atg** [zacanger/profane-words#13]
I read through the entire list from start to finish, to look for false positives.

A few words which are definitely not profane:

```
crash
funeral
trombone
propaganda
```

A few words that are violent, but not profane, insofar as you might see them in a news report:

```
homicide
murder
thug
explosion
killer
slaughter
```

Words which are not inherently profane: you can use them in a non-profane sentence.

```
whiz
throat
shaved
thrust
suck
slant
seduce
prick
stupid
gross
feces
dummy
demon
cox
climax
snatch
```

There's also a few words for foreigners like [`gringo`](https://en.wikipedia.org/wiki/Gringo) and [`bule`](https://en.wikipedia.org/wiki/Bule_(term)) which people debate, but IMO are not really more offensive in their respective languages than the word "foreigner" is in English.

**Comment by zautumnz** [comment]
Thanks! Fixed in d859e9918482017dbc4932a9f89cf125c492a20e. I'm sure there are more false positives — it's a long list, and mostly based on other lists from around the internet — so please feel free to open a new issue or a pull request if any are causing issues.

**Comment by Lilja** [comment]
Something I recently found was "dp" and "wn". WN apparently means white nationalists, [DP I'm unsure of](https://www.urbandictionary.com/define.php?term=DP)

**Comment by zautumnz** [comment]
@Lilja see [the second page](https://www.urbandictionary.com/define.php?term=DP&page=2). But I removed that one just now, because it's pretty vague. Also removed WN, because it's also ambiguous.
