### ISSUE TITLE
False positives (and false negatives)

### ISSUE THREAD

**Issue by JakeSteam** [zacanger/profane-words#14]
Hey, I recently used this list [for a project](https://github.com/JakeSteam/WordNetToSQLite), just thought I'd let you know the false positives & false negatives I ended up removing.

The project uses [a fork of WordNet](https://github.com/globalwordnet/english-wordnet), and runs words & definitions through this filter with only lowercase words taken (so no proper nouns etc).

Obviously how profane a word is depends on the project, the audience, the context, even the font, but sharing my changes in case someone else wants a slightly less restrictive list! Some of them were particularly spammy in my dataset (e.g. "illegal", "terrorist"). 

False negatives:

```
mindfuck
pussyfuck
```

False positives
```
666
abuse
Aeolus
aroused
ass
asses
backdoor
bagging
banger
banging
barf
bawdy
blackout
blacks
bloody
bodily
bombing
boned
bong
bookie
boozy
cervix
chute
commie
crabs
cracker
crotch
cumquat
damnation
damned
demon
domination
enlargement
erect
erotic
escort
flange
fungus
gangsta
gob
harem
hell
hijacking
hoar
hoe
homey
horny
illegal
inbred
interracial
jerk
jerk
jugs
kicking
kumquat
licking
lingerie
loin
loins
lovemaking
lust
lusty
mormon
mung
nad
nappy
nasty
necked
niggling
nip
nymph
orally
orifice
pasty
pasty
pistol
premature
pud
puke
pule
pussycat
redneck
rigger
sac
screwed
screwing
seduce
shrimping
slopes
smack
smoker
smut
snigger
sooty
spade
spades
spitter
steamy
stoned
stoned
stringer
stroke
sucker
sucking
sucks
taboo
teat
terror
terrorist
tinkle
tinkle
toke
tramp
trashy
triplex
trojan
undressing
virgin
vodka
vomit
wad
whites
yeasty
```

**Comment by zautumnz** [comment]
Thank you, addressed in v1.6.0 — a few you identified as positives, I didn't remove purely just based on judgement, but most removed, and the false negatives you found fixed as well.
