### ISSUE TITLE
This appears to be filled with false positives.

### ISSUE THREAD

**Issue by jeffmcmahan** [zacanger/profane-words#3]
Pick anywhere and start reading. ~15% of the words are nowhere near profane.

protestant
republican
weed
radical
racist
violence
punch
prude
primetime
piercing
peck
palestinian
nfsw
nook
narcotic
napalm
...

**Comment by jeffmcmahan** [comment]
... athletesfoot?

**Comment by zautumnz** [comment]
This list is a compilation of a couple of other lists. It could probably do with another good audit.

**Comment by zautumnz** [comment]
Published 1.2.2 with fixes.

**Comment by shez1983** [comment]
just wanted to add in some context you would never use these words 'violence etc etc' say on airbnb, but in other context they would be valid.. :/
